import { Opinion, Debate, UserProfile, LeaderboardEntry } from "./types";

function generatePriceHistory(base: number, length: number = 30): number[] {
  const history: number[] = [];
  let price = base * 0.6;
  for (let i = 0; i < length; i++) {
    price = Math.max(1, price + (Math.random() - 0.45) * base * 0.08);
    history.push(Math.round(price * 10) / 10);
  }
  history[history.length - 1] = base;
  return history;
}

export const opinions: Opinion[] = [
  {
    id: "op-1",
    content: "AI将在5年内取代80%的初级程序员岗位",
    author: "深度思考者",
    authorAvatar: "🧠",
    topic: "AI & 职业",
    price: 67,
    previousPrice: 52,
    priceHistory: generatePriceHistory(67),
    holders: 342,
    debates: 18,
    createdAt: "2026-03-20",
    trending: true,
  },
  {
    id: "op-2",
    content: "远程办公将成为主流，写字楼将大量空置",
    author: "未来观察",
    authorAvatar: "🔭",
    topic: "职场趋势",
    price: 45,
    previousPrice: 48,
    priceHistory: generatePriceHistory(45),
    holders: 189,
    debates: 12,
    createdAt: "2026-03-18",
    trending: false,
  },
  {
    id: "op-3",
    content: "比特币2027年底将突破50万美元",
    author: "币圈老韭菜",
    authorAvatar: "💰",
    topic: "加密货币",
    price: 89,
    previousPrice: 71,
    priceHistory: generatePriceHistory(89),
    holders: 567,
    debates: 31,
    createdAt: "2026-03-15",
    trending: true,
  },
  {
    id: "op-4",
    content: "短视频正在摧毁年轻人的深度思考能力",
    author: "教育守望者",
    authorAvatar: "📚",
    topic: "社会观察",
    price: 34,
    previousPrice: 30,
    priceHistory: generatePriceHistory(34),
    holders: 421,
    debates: 24,
    createdAt: "2026-03-19",
    trending: true,
  },
  {
    id: "op-5",
    content: "中国新能源汽车将在3年内占领全球50%市场",
    author: "产业分析师",
    authorAvatar: "🚗",
    topic: "产业趋势",
    price: 56,
    previousPrice: 61,
    priceHistory: generatePriceHistory(56),
    holders: 298,
    debates: 15,
    createdAt: "2026-03-17",
    trending: false,
  },
  {
    id: "op-6",
    content: "AGI不会在2030年前实现，当前AI只是模式匹配",
    author: "冷静派",
    authorAvatar: "🧊",
    topic: "AI & 技术",
    price: 41,
    previousPrice: 38,
    priceHistory: generatePriceHistory(41),
    holders: 156,
    debates: 22,
    createdAt: "2026-03-21",
    trending: false,
  },
  {
    id: "op-7",
    content: "元宇宙已死，空间计算才是下一个风口",
    author: "趋势猎手",
    authorAvatar: "🎯",
    topic: "科技趋势",
    price: 28,
    previousPrice: 23,
    priceHistory: generatePriceHistory(28),
    holders: 134,
    debates: 8,
    createdAt: "2026-03-22",
    trending: false,
  },
  {
    id: "op-8",
    content: "2026年是独立开发者最好的时代，AI让一个人等于一个团队",
    author: "Solo Maker",
    authorAvatar: "⚡",
    topic: "创业",
    price: 73,
    previousPrice: 58,
    priceHistory: generatePriceHistory(73),
    holders: 445,
    debates: 19,
    createdAt: "2026-03-16",
    trending: true,
  },
];

export const debates: Debate[] = [
  {
    id: "db-1",
    opinionId: "op-1",
    opinionContent: "AI将在5年内取代80%的初级程序员岗位",
    topic: "AI & 职业",
    status: "ongoing",
    proSide: { label: "赞同", participants: 45, totalBet: 2340 },
    conSide: { label: "反对", participants: 38, totalBet: 1890 },
    totalPool: 4230,
    startTime: "2026-03-24 10:00",
    messages: [
      {
        id: "msg-1",
        author: "深度思考者",
        avatar: "🧠",
        side: "pro",
        content:
          "看看GitHub Copilot的进化速度，从补全代码到理解整个项目架构，再到自主实现feature。Devin已经能独立完成简单的全栈任务。这个趋势不可逆。",
        likes: 67,
        timestamp: "10:05",
      },
      {
        id: "msg-2",
        author: "资深码农",
        avatar: "👨‍💻",
        side: "con",
        content:
          "AI写的代码看着能跑，但在生产环境里全是坑。需求理解、架构决策、跨团队沟通——这些才是程序员的核心价值，AI目前完全做不到。",
        likes: 54,
        timestamp: "10:12",
      },
      {
        id: "msg-3",
        author: "AI分身·锐评家",
        avatar: "🤖",
        side: "pro",
        content:
          "反方说的'核心价值'正在被重新定义。当AI能处理80%的编码工作时，剩下的20%确实需要人——但那不再叫'初级程序员'了，那叫'AI训练师'。岗位不是消失，是变形。",
        likes: 89,
        timestamp: "10:20",
        isAI: true,
      },
      {
        id: "msg-4",
        author: "产品经理视角",
        avatar: "📋",
        side: "con",
        content:
          "作为PM，我每天还是需要和真人开发沟通需求细节。AI对模糊需求的理解力远不如一个有经验的初级开发。而且，谁来review AI写的代码？还是人。",
        likes: 43,
        timestamp: "10:28",
      },
    ],
  },
  {
    id: "db-2",
    opinionId: "op-3",
    opinionContent: "比特币2027年底将突破50万美元",
    topic: "加密货币",
    status: "recruiting",
    proSide: { label: "会突破", participants: 23, totalBet: 1200 },
    conSide: { label: "不可能", participants: 15, totalBet: 780 },
    totalPool: 1980,
    startTime: "2026-03-25 14:00",
    messages: [],
  },
  {
    id: "db-3",
    opinionId: "op-4",
    opinionContent: "短视频正在摧毁年轻人的深度思考能力",
    topic: "社会观察",
    status: "voting",
    proSide: { label: "确实在摧毁", participants: 56, totalBet: 3100 },
    conSide: { label: "危言耸听", participants: 41, totalBet: 2200 },
    totalPool: 5300,
    startTime: "2026-03-23 09:00",
    endTime: "2026-03-24 09:00",
    messages: [],
  },
];

export const currentUser: UserProfile = {
  name: "观点猎人",
  avatar: "🎯",
  balance: 1580,
  totalProfit: 2340,
  rank: 127,
  totalUsers: 5200,
  percentile: 97.6,
  debatesWon: 14,
  debatesTotal: 21,
  holdings: [
    {
      opinionId: "op-1",
      opinionContent: "AI将在5年内取代80%的初级程序员岗位",
      buyPrice: 42,
      currentPrice: 67,
      quantity: 5,
      profit: 125,
      profitPercent: 59.5,
    },
    {
      opinionId: "op-3",
      opinionContent: "比特币2027年底将突破50万美元",
      buyPrice: 78,
      currentPrice: 89,
      quantity: 3,
      profit: 33,
      profitPercent: 14.1,
    },
    {
      opinionId: "op-8",
      opinionContent: "2026年是独立开发者最好的时代",
      buyPrice: 65,
      currentPrice: 73,
      quantity: 8,
      profit: 64,
      profitPercent: 12.3,
    },
    {
      opinionId: "op-5",
      opinionContent: "中国新能源汽车将占领全球50%市场",
      buyPrice: 63,
      currentPrice: 56,
      quantity: 4,
      profit: -28,
      profitPercent: -11.1,
    },
  ],
  badges: ["🏆 辩论之王", "📈 慧眼识珠", "🔥 连胜达人"],
};

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, name: "观点之神", avatar: "👑", value: 28900, winRate: 89, badge: "🏆" },
  { rank: 2, name: "逻辑大师", avatar: "🧮", value: 24500, winRate: 85, badge: "🥈" },
  { rank: 3, name: "趋势先知", avatar: "🔮", value: 21200, winRate: 82, badge: "🥉" },
  { rank: 4, name: "理性之光", avatar: "💡", value: 18700, winRate: 78 },
  { rank: 5, name: "深度思考者", avatar: "🧠", value: 16400, winRate: 76 },
  { rank: 6, name: "币圈老韭菜", avatar: "💰", value: 15100, winRate: 74 },
  { rank: 7, name: "Solo Maker", avatar: "⚡", value: 13800, winRate: 71 },
  { rank: 8, name: "未来观察", avatar: "🔭", value: 12500, winRate: 69 },
  { rank: 9, name: "数据说话", avatar: "📊", value: 11200, winRate: 67 },
  { rank: 10, name: "观点猎人", avatar: "🎯", value: 9800, winRate: 66 },
];
